---
title: ""
pagetitle: "Credits"
title-block-style: none
---

This website was built with [Quarto](https://quarto.org), which in turn I could only navigate in a time-efficient manner because of the help of an LLM. 

I owe the original impulse towards this design to my colleague [Eric Pacuit](https://pacuit.org). 

The photos on the homepage and the presentations page are by [Natasha Korotkova](https://natasha-korotkova.github.io). They were taken respectively in 2022 in Konstanz, and at the 2024 Amsterdam Colloquium. 

The pensive photo on my contact page was taken by [Jessica Collins](https://jessica-collins.co) at the 2025 Pacific APA in San Francisco. 

I'm forever grateful to my amazing co-authors. In reverse chronological order, [Paolo Santorio](santorio.net), [Alexis Wellwood](https://www.semantics.land), [Lance Rips](https://sites.northwestern.edu/ripslab/), [Nicholas Leonard](https://nickleonardphilosophy.weebly.com), [Simon Goldstein](https://www.simondgoldstein.com), [Ray Briggs](https://philosophy.uchicago.edu/ray-briggs), [Kenny Easwaran](https://www.kennyeaswaran.org), [Branden Fitelson](https://fitelson.org), [Magda Kaufmann](https://magdalena-kaufmann.uconn.edu), [Stefan Kaufmann](https://stefan-kaufmann.uconn.edu), [Marc Pauly](https://philpeople.org/profiles/marc-pauly) and [Josh Snyder](https://commaok.xyz).
