---
title: "Curriculum Vitae"
pagetitle: "Fabrizio Cariani – Curriculum Vitae"
title-block-style: none
---

::: columns
::: {.column width="20%"}
**EMPLOYMENT**
:::

::: {.column width="80%"}
**University of Maryland, College Park**

- **Professor and Chair**, Philosophy *(2024– )*
- **Professor**, Philosophy *(2022– )*
- **Affiliate Faculty**, AIM *(2024– )*
- **Associate Professor**, Philosophy *(2020–2022)*

**Northwestern University**

- **Associate Professor**, Philosophy *(2016–2020)*
- **Assistant Professor**, Philosophy *(2010–2016)*
- **College Fellow (tenure track)**, WCAS *(2009–2010)*
- **Affiliated Faculty**, Linguistics *(2010–2020)*
- **Affiliated Faculty**, Cognitive Science *(2014–2020)*
:::
:::

---

::: columns
::: {.column width="20%"}
**EDUCATION**
:::

::: {.column width="80%"}
**University of California, Berkeley**  
Ph.D. in Logic & Methodology of Science *(2009)*

**University of Bologna**  
B.A. in Philosophy, *cum laude* *(2003)*
:::
:::
---

::: columns
::: {.column width="20%"}
**SPECIALIZATIONS**
:::

::: {.column width="80%"}
Philosophy of Language; Epistemology; Philosophical Logic.
:::
:::

::: columns
::: {.column width="20%"}
**COMPETENCIES**
:::

::: {.column width="80%"}
Cognitive Science; Decision Theory and Social Choice Theory; Mathematical Logic; Metaphysics; Philosophy of Mathematics; Philosophy of Science; Philosophical Themes in Artificial Intelligence.
:::
:::

---

::: columns
::: {.column width="20%"}
**RESEARCH AWARDS**
:::

::: {.column width="80%"}

**Mellon Foundation**, *New Directions Fellowship* *(2017–2019)*.  
Two-year fellowship to acquire post-PhD training in Computer Science (specifically AI & agent-based modeling), Psychology, and Statistics ($196,000).

**Mellon Foundation**, *Sawyer Seminar in Social Epistemology*.  
Co-winner of a $175,000 grant (with Sanford Goldberg and Jennifer Lackey, Northwestern University) to organize a series of workshops on topics in social epistemology.

:::
:::

---

::: columns
::: {.column width="20%"}
**TEACHING AWARDS**
:::

::: {.column width="80%"}

*Faculty Honor Roll*, Associated Student Government of Northwestern University *(2018–2019)*.

*Outstanding Graduate Student Instructor Award*, UC Berkeley, Philosophy *(2004)*.

:::
:::

***
::: columns
::: {.column width="20%"}
**PUBLICATIONS**
:::

::: {.column width="80%"}

:::
:::

::: columns
::: {.column width="20%"}
**BOOKS**
:::

::: {.column width="80%"}



1. **[The Modal Future](https://www.cambridge.org/core/books/modal-future/8C73F378DAF8A9C20DDBA54E46D95982)**.  
    *Cambridge University Press*, 2021.

:::
:::


::: columns
::: {.column width="20%"}
**ARTICLES**
:::

::: {.column width="80%"}

2. **[Anankastic Conditionals and the Default Theory of Reasons](https://philarchive.org/archive/CARACA-22)**.  
    Forthcoming in *Linguistics and Philosophy*.

1. **[Normative Credences Are Not Classical](https://philpapers.org/rec/CARNCA-10)**.  
    Forthcoming in *Analysis*.

1. **[Future Displacement and Modality](https://philpapers.org/rec/CARFDA-4)**.  
    In *Oxford Handbook of Contemporary Philosophy of Language*  
    (E. Lepore & U. Stojnić, eds.), 2025.

1. **[Intention Reconsideration in Artificial Agents: A Structured Account](https://philpapers.org/rec/CARIRI-5)**.  
    *Philosophical Studies*, special issue on *Normative Theory and AI*,  
    182, pp. 205–228, 2025.

1. **[Confidence Reports](https://semprag.org/index.php/sp/article/view/sp.17.14/3103)**  
    (with Paolo Santorio and Alexis Wellwood).  
    *Semantics & Pragmatics*, 17(14), 2024.

1. **[Experimenting with (Conditional) Perfection](https://philpapers.org/archive/CAREWC.pdf)**  
    (with Lance J. Rips).  
    In *Conditionals: Logic, Semantics, Psychology*  
    (S. Kaufmann, D. Over & G. Sharma, eds.), 2023.

1. **[On Stalnaker’s *Indicative Conditionals*](https://philpapers.org/archive/CAROSQ.pdf)**.  
    In *A Reader’s Guide to Classic Papers in Formal Semantics*, SLAP 100  
    (L. McNally & Z. Gendler Szabó, eds.), pp. 387–406, 2022.

1. **[Human Foreknowledge](https://philpapers.org/archive/CARHF-2.pdf)**.  
    *Philosophical Perspectives*, 35(1), pp. 50–69, 2021.

1. **[Deontic Logic and Natural Language](https://philpapers.org/archive/CARDLA-7.pdf)**.  
    In *Handbook of Deontic Logic*, vol. 2  
    (D. Gabbay, J. Horty, X. Parent, R. van der Meyden & L. van der Torre, eds.),  pp. 499–548, 2021.

1. **[Normative Indeterminacy in the Epistemic Domain](https://philpapers.org/archive/LEONII.pdf)**  
    (with Nick Leonard).  
    In *Epistemic Dilemmas: New Arguments, New Angles*  
    (K. McCain, S. Stapleford & M. Steup, eds.), 2021.

1. **[On Predicting](https://quod.lib.umich.edu/e/ergo/12405314.0007.011?view=text;rgn=main)**.  
    *Ergo*, 7(11), 2020.

1. **[Conditional Heresies](https://philpapers.org/archive/CARCH-5.pdf)**  
    (with Simon Goldstein).  
    *Philosophy and Phenomenological Research*, 101(2),  
    pp. 251–282, 2020.

1. **[Assertion and Modality](https://philpapers.org/archive/CARAAM-13.pdf)**.  
    In *Oxford Handbook of Assertion* (Sanford Goldberg, ed.),  
    Oxford University Press, pp. 505–528, 2020.

1. **[A Context Principle for the Twenty-first Century](https://philpapers.org/archive/CARACP-3.pdf)**.  
    In *Eva Picardi: Language, Analysis and History*  
    (A. Coliva, P. Leonardi & S. Moruzzi, eds.),  
    Palgrave Macmillan, pp. 183–203, 2018.

1. **[*Will* Done Better: Selection Semantics, Future Credence and Indeterminacy](https://philpapers.org/archive/CARWDB-6.pdf)**  
    (with Paolo Santorio).  
    *Mind*, 127(505), pp. 129–165, 2018.

1. **[Credences, Chances, and Circles](https://philpapers.org/archive/CARCCA-14.pdf)**.  
    *Episteme*, 14(1), pp. 49–58, 2017.  
    (Special issue on Richard Pettigrew’s *Accuracy and the Laws of Credence*.)

1. **[Choice Points for a Modal Theory of Disjunction](https://philpapers.org/archive/CARCPF.pdf)**.  
    *Topoi*, 36(1), pp. 171–181, 2017.

1. **[Consequence and Contrast in Deontic Semantics](https://philpapers.org/archive/CARCAC-19.pdf)**.  
    *The Journal of Philosophy*, 113(8), pp. 396–416, 2016.

1. **[Conditionals, Context and the Suppression Effect](https://philpapers.org/archive/CARCCA-19.pdf)**  
    (with Lance J. Rips).  
    *Cognitive Science*, 2016.

1. **[Local Supermajorities](https://philpapers.org/archive/CARLS-2.pdf)**.  
    *Erkenntnis*, 81(2), pp. 391–406, 2016.

1. **[Deontic Modals and Probabilities: One Theory to Rule Them All?](https://philpapers.org/archive/CARDMA-5.pdf)**.  
    In *Deontic Modality* (N. Charlow & M. Chrisman, eds.),  
    Oxford University Press, pp. 11–46, 2016.  
    Reprinted in *The Philosopher’s Annual* 36.

1. **[Attitudes, Deontics and Semantic Neutrality](http://cariani.org/files/ADS.cariani.pdf)**.  
    *Pacific Philosophical Quarterly*, 95(4), pp. 491–511, 2014.

1. **[Individual Coherence and Group Coherence](http://fitelson.org/icagc.pdf)**  
    (with Ray Briggs, Kenny Easwaran & Branden Fitelson).  
    In *Essays in Collective Epistemology* (J. Lackey, ed.),  
    Oxford University Press, pp. 215–239, 2014.

1. **[Epistemic and Deontic *Should*](https://philpapers.org/archive/CAREAD-5.pdf)**.  
    *Thought*, 2(1), pp. 73–84, 2013.

1. **[Deliberative Modality under Epistemic Uncertainty](http://cariani.org/files/DM.ckk.pdf)**  
    (with Magdalena Kaufmann & Stefan Kaufmann).  
    *Linguistics and Philosophy*, 36(3), pp. 225–259, 2013.

1. **[Aggregating with Reason(s)](https://philpapers.org/archive/CARAWR.pdf)**.  
    *Synthese*, 190(15), pp. 3123–3147, 2013.

1. **[*Ought* and Resolution Semantics](https://philpapers.org/archive/CAROAR-2.pdf)**.  
    *Noûs*, 47(3), pp. 534–558, 2013.

1. **[Epistemology in *Group Agency*: Six Objections in Search of the Truth](http://cariani.org/files/EIGA.cariani.pdf)**.  
    *Episteme*, 9(3), pp. 255–269, 2012.

1. **[Judgment Aggregation](http://cariani.org/files/JA.cariani.pdf)**.  
    *Philosophy Compass*, 6(1), pp. 22–32, 2011.

1. **[Decision Framing in Judgment Aggregation](http://cariani.org/files/DFJA.cariani.pdf)**.  
    (with Marc Pauly & Josh Snyder).  
    *Synthese*, 163, pp. 1–24, 2008.  
    Reprinted in *The Philosopher’s Annual* 28.

:::
:::


::: columns
::: {.column width="20%"}
**CONFERENCE PROCEEDINGS**
:::

::: {.column width="80%"}

32. *Default Premise Semantics for Anankastic Conditionals*.  
    *Proceedings of the Amsterdam Colloquium*, 2024.

1. *Past-Future Asymmetries, Evidential Grounding, and Projection*.  
    *Proceedings of the Amsterdam Colloquium*, 2022.

1. *Positive gradable adjective ascriptions with states, not degrees*  
    (with Paolo Santorio & Alexis Wellwood).  
    Forthcoming in *Proceedings of Sinn und Bedeutung 2022*.

1. **[Conditionals in Selection Semantics](http://cariani.org/files/CSS.AC.2019.pdf)**.  
    *Proceedings of the 2019 Amsterdam Colloquium*.

1. **[Homogeneous Alternative Semantics](http://cariani.org/files/CarianiGoldstein.AC.2017.pdf)**  
    (with Simon Goldstein).  
    *Proceedings of the 2017 Amsterdam Colloquium*.

1. **[Selection Semantics for *Will*](http://cariani.org/files/ssw.ac.pdf)**  
    (with Paolo Santorio).  
    *Proceedings of the 2015 Amsterdam Colloquium*, pp. 80–89.

:::
:::


::: columns
::: {.column width="20%"}
**REVIEWS**
:::

::: {.column width="80%"}

38. **Review of Patrick Todd’s *The Open Future***.  
    *The Philosophical Review*, 132(4), pp. 650–654, 2023.

1. **[Review of Robert C. Stalnaker’s *Knowledge and Conditionals*](https://ndpr.nd.edu/news/knowledge-and-conditionals-essays-on-the-structure-of-inquiry/?fbclid=IwAR2CH61TD6gk2nS8akSgW7jOAgXdpsvUy91qt6IkvLBcI5ph_72Wf78IA1g)**.  
    *Notre Dame Philosophical Reviews*, 9/2020.

1. **[Comments on Roger White’s “The Problem of the Problem of Induction”](http://cariani.org/files/White.comments.cariani.pdf)**.  
    *Episteme*, 12(2), pp. 291–296, 2015.

1. **[Review of François Recanati’s *Truth-Conditional Pragmatics*](http://cariani.org/files/RR.cariani.pdf)**.  
    *Philosophical Quarterly*, 62(247), pp. 415–418, 2012.

:::
:::


::: columns
::: {.column width="20%"}
**IN ITALIAN**
:::

::: {.column width="80%"}

42. *Modus Ponens*.   *Aphex* (blind refereed), 7, 2013.

:::
:::


::: columns
::: {.column width="20%"}
**EDITED PROCEEDINGS**
:::

::: {.column width="80%"}

43. *Proceedings of DEON 2014*.  
    Co-edited with Davide Grossi, Joke Meheus & Xavier Parent.  
    *Lecture Notes in Artificial Intelligence* 8554, Springer.

:::
:::

***

::: columns
::: {.column width="20%"}
**VISITING**
:::

::: {.column width="80%"}

**University of Michigan**, Philosophy Department.  
Visiting Scholar *(Fall 2013)*.

**Tilburg University**, Philosophy Department.  
Short-term Visiting Fellow *(September–October 2010)*.

**Australian National University**, Research School for the Social Sciences.  
Visiting Student in the Philosophy Program  
*(July–August 2007; July 2008)*.

:::
:::

***

::: columns
::: {.column width="20%"}
**EDITORIAL ACTIVITY**
:::

::: {.column width="80%"}

**Editorships and Editorial Boards**

- *Linguistics and Philosophy*, Editorial Board Member *(2019– )*.
- *Philosophers’ Imprint*, Editor *(2018–2024)*.



:::
:::

***

::: columns
::: {.column width="20%"}
**REVIEWING**
:::

::: {.column width="80%"}

**Journal Reviewing**  
(Served as reviewer, often multiple times, for the journals below)

*American Philosophical Quarterly*; *Analysis*; *Analytic Philosophy*;  
*Australasian Journal of Philosophy*; *Canadian Journal of Philosophy*;  
*Cognition*; *Dialectica*; *Economics and Philosophy*; *Episteme*;  
*Erkenntnis*; *Ergo*; *European Journal for the Philosophy of Science*;  
*Ethics*; *Glossa*; *Journal of the American Philosophical Association*;  
*Journal of Ethics and Social Philosophy*; *Journal of Philosophical Logic*;  
*Journal of Philosophical Research*; *The Journal of Philosophy*;  
*Journal of Semantics*; *Linguistics and Philosophy*;  
*Logic Journal of the IGPL*; *Mathematical Methods in the Social Sciences*;  
*Mind*; *Mind and Language*; *Noûs*; *Pacific Philosophical Quarterly*;  
*Philosophy Compass*; *Philosophers’ Imprint*; *The Philosophical Review*;  
*Philosophy and Phenomenological Research*; *Philosophical Studies*;  
*Philosophy of Science*; *Ratio*; *Res Philosophica*;  
*The Review of Symbolic Logic*; *Semantics & Pragmatics*;  
*Studia Logica*; *Synthese*; *Theoria*; *Thought*.

**Reviewing for Edited Volumes**

*Cambridge Handbook of Modality*;
*Blackwell Companion to Philosophy of Language*;  
*Topics in Contemporary Philosophy*;  
*Essays in Collective Epistemology*;  
*Deontic Modality*;  
*Conditionals*.

**Book Proposal Reviewer**

*Oxford University Press* *(x5)*; *Routledge*.

**Fellowship and Grant Reviewing**

- Flanders Research Foundation  
- Research Committee of Lingnan University *(x2)*  
- Austrian Science Fund  
- University of Maryland, Grand Challenges Individual Competitions  
- Core Fellowship Reviewer, Helsinki Collegium

:::
:::

::: columns
::: {.column width="20%"}
**ORGANIZING**
:::

::: {.column width="80%"}

**Conference Organization**  
(Main organizer, e.g. program committee co-chair)

- DEON 2014  
- Northwestern University, Deontic Modality Workshop *(2013)*  
- Northwestern University, Philosophy of Language Pre-APA Conference *(2012)*

**Program Committee Member**

AIES *(2021)*;  
Formal Approaches to Rationality and Meaning (FARM) *(2025)*;  
Formal Ethics *(2020, 2024)*;  
Amsterdam Colloquium *(2019, 2022)*;  
Central APA *(2015, 2018)*;  
SALT *(2016–2019)*;  
DEON *(2016, 2018, 2023)*;  
Lori-V *(2015)*;  
FEW *(2014–2016; 2018–2019; 2024)*;  
Norms, Actions and Games *(2014)*;  
ESSLLI Workshop on Logical Models of Group Decision Making *(2013)*.

**Co-organizer**

UC Berkeley Townsend Center Working Group in  
*History and Philosophy of Logic, Mathematics and Science* *(2005–2009)*.

:::
:::

::: columns
::: {.column width="20%"}
**UNIVERSITY SERVICE**
:::

::: {.column width="80%"}

**Main Departmental Roles**

- **Department Chair**, University of Maryland *(2024– )*
- **BA in AI Design Committee**, University of Maryland *(2023– )*
- **Director of Graduate Studies**, University of Maryland *(2022–2024)*
- **Faculty Advisory Committee**, University of Maryland *(2022–2024)*
- **Philosophy Department Committee on Diversity, Equity, and Inclusion**,  
  University of Maryland *(2022–2024)*
- **Director of Instructor Training**, UMD Philosophy *(2020–2022)*

**Committee Roles**

- **Chair**, Search Committee for Chair of the Department of Communication,  
  University of Maryland *(2025–2026)*
- **Chair**, APT Promotion Subcommittee (Full Professor Case),  
  University of Maryland *(2023)*
- **Chair**, APT Promotion Subcommittee (Full Professor Case),  
  University of Maryland *(2022)*
- **Member**, ARHU Doctoral Education Task Force,  
  University of Maryland *(2021)*
- **Member**, Open Rank M&E Search Committee,  
  Northwestern University, Philosophy *(2016–2017)*
- **Member**, Graduate Admission Committee,  
  Northwestern University, Philosophy *(2015–2016)*
- **Member**, Open Rank M&E Search Committee,  
  Northwestern University, Philosophy *(2015–2016)*
- **Member**, Mellon Sawyer Seminar Postdoctoral Search Committee,  
  Northwestern University, Philosophy *(2013–2014)*
- **Chair**, Speaker Series Committee,  
  Northwestern University, Philosophy *(2012–2013)*
- **Member**, Undergraduate Committee,  
  Northwestern University, Philosophy *(2011–2012; 2014–2015; 2016–2017; 2019–2020)*
- **Member**, Space Committee,  
  Northwestern University, Philosophy *(2011–2012)*
- **Logic Coordinator**,  
  Northwestern University, Philosophy *(2010–2020)*
- **Member**, Senior M&E Search Committee,  
  Northwestern University, Philosophy *(2009–2010)*

:::
:::