---
title: ""
pagetitle: "Teaching"
title-block-style: none
---

## Undergraduate

### University of Maryland

- **The Philosophy in AI** (Fall 2020; Fall 2021; Fall 2023, Fall 2025)
As of Fall 2025, this course is renamed *AI and the Human Experience*.  
- **Symbolic Logic II** (Spring 2024)  
- **Decision Theory** (Fall 2023)  
- **Bayesian Epistemology** (Fall 2022)  
- **Philosophy of the Universe** (Spring 2021; Fall 2022)  
- **The Logic of Types, Classes, and Properties and Its Applications** (Fall 2021)

### Northwestern University

- **Philosophy of the Universe** (Fall 2019)  
- **The Philosophy in AI** (Spring 2019)  
- **Counterfactuals** (Spring 2016)  
- **Philosophy of Mathematics** (Spring 2017; Fall 2010)  
- **Practical Reasoning and Choice** (Spring 2020; Fall 2016; Fall 2014; Fall 2012; Fall 2011; Spring 2010) [This is what my decision theory course was called at NU]
- **Introduction to Metaphysics** (Spring 2020; Fall 2015; Winter 2014; Winter 2012)  
- **Elementary Logic II** (Spring 2018; Winter 2012; Spring 2011; Spring 2010)  
- **Elementary Logic I** (Summer 2020; Summer 2019; Fall 2016; Fall 2014; Summer 2013)  
- **Scientific Reasoning** (Spring 2013)  
- **Freshman Seminar: Objective vs. Subjective** (Fall 2012; Spring 2011)  
- **Freshman Seminar: Methods of Inquiry** (Spring 2016)



## Graduate Seminars

### University of Maryland

- **Large Language Models: Language, Rationality, and Cognition** (Spring 2025)  
- **Evidence and Language** (Spring 2023)  
- **The Modal Future** (Fall 2020)

### Northwestern University

- **The Modal Future** (Fall 2019)  
- **Counterfactuals and Probability** (Spring 2018)  
- **Job Market Preparation Seminar** (Spring 2017)  
- **Future Contingents** (Fall 2015)  
- **Formal Epistemology: Foundations and Research Perspectives** (Spring 2015)  
- **First-Year Proseminar: Classics of Philosophy of Language** (Winter & Spring 2014)  
- **The Language of Deliberation** (Spring 2013)  
- **Reasoning and Rationality** (Fall 2011)  
- **Metasemantics** (Fall 2010)



## Other Teaching

- **Modality, Evidentiality, and Futurity**, NASSLLI 2022, *(co-taught with Natasha Korotkova)*
- **Counterfactuals and Probability**, ESSLLI 2019,  *(co-taught with Paolo Santorio)*
- **Deontic Logic**, PIKSI–Logic 2018, *(co-taught with Jennifer Carr)*
- **Foundational and Empirical Questions in Degree Semantics, with Modality as a Case Study**, NASSLLI 2016, *(co-taught with Paolo Santorio and Alexis Wellwood)*
